[package]
name = "icrn_dw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
chrono = "0.4.26"
md5 = "0.7.0"
